repos:
  # -------------------------------------------------------------------
  # 1. Golang built-in tools
  # -------------------------------------------------------------------
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
        pass_filenames: false
        require_serial: true
        files: ^go\.mod$

      - id: go-build
        pass_filenames: false
        require_serial: true
        files: ^.*


  # -------------------------------------------------------------------
  # 2. GolangCI-Lint
  # -------------------------------------------------------------------
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --timeout 5m ./...
        language: system
        pass_filenames: false
        types: [go]


  # -------------------------------------------------------------------
  # 3. Hygiene checks
  # -------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=200"]


  # -------------------------------------------------------------------
  # 4. Conventional Commits
  # -------------------------------------------------------------------
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
